include: _default_template_yaml_local
dataset_path: $LMMS_EVAL_MVBENCH_DATASET_DIR/object_interaction
task: mvbench_object_interaction_local
dataset_name: object_interaction
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: object_interaction
    post_prompt: "Only give the best option.\n"
