include: _default_template_yaml_local
dataset_path: $LMMS_EVAL_MVBENCH_DATASET_DIR/fine_grained_pose
task: mvbench_fine_grained_pose_local
dataset_name: fine_grained_pose
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: fine_grained_pose
    post_prompt: "Only give the best option.\n"
