include: _default_template_yaml_local
dataset_path: $LMMS_EVAL_MVBENCH_DATASET_DIR/moving_direction
task: mvbench_moving_direction_local
dataset_name: moving_direction
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: moving_direction
    post_prompt: "Only give the best option.\n"
