include: _reasoning_template_yaml
task: mvbench_character_order_future_l1
dataset_name: character_order
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: character_order
    pre_prompt: ""
    post_prompt: ""
