include: _reasoning_template_yaml
task: mvbench_fine_grained_action_future_l1
dataset_name: fine_grained_action
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: fine_grained_action
    pre_prompt: ""
    post_prompt: ""
