include: _reasoning_template_yaml
task: mvbench_counterfactual_inference_future_l1
dataset_name: counterfactual_inference
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: counterfactual_inference
    pre_prompt: ""
    post_prompt: ""
