include: _reasoning_template_yaml
task: mvbench_action_prediction_thinking
dataset_name: action_prediction
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_prediction
    pre_prompt: "You FIRST think about the reasoning process as an internal monologue and then provide the final answer.\nThe reasoning process MUST BE enclosed within <reason> </reason> tags. After all thinking is complete, place the final answer inside `<answer>option's letter from the given choices</answer>`"
    post_prompt: ""
